export const SCARD_S_SUCCESS = 0x0000_0000;
export const SCARD_F_INTERNAL_ERROR = 0x8010_0001;
export const SCARD_E_CANCELLED = 0x8010_0002;
export const SCARD_E_INVALID_HANDLE = 0x8010_0003;
export const SCARD_E_INVALID_PARAMETER = 0x8010_0004;
export const SCARD_E_INVALID_TARGET = 0x8010_0005;
export const SCARD_E_NO_MEMORY = 0x8010_0006;
export const SCARD_F_WAITED_TOO_LONG = 0x8010_0007;
export const SCARD_E_INSUFFICIENT_BUFFER = 0x8010_0008;
export const SCARD_E_UNKNOWN_READER = 0x8010_0009;
export const SCARD_E_TIMEOUT = 0x8010_000A;
export const SCARD_E_SHARING_VIOLATION = 0x8010_000B;
export const SCARD_E_NO_SMARTCARD = 0x8010_000C;
export const SCARD_E_UNKNOWN_CARD = 0x8010_000D;
export const SCARD_E_CANT_DISPOSE = 0x8010_000E;
export const SCARD_E_PROTO_MISMATCH = 0x8010_000F;
export const SCARD_E_NOT_READY = 0x8010_0010;
export const SCARD_E_INVALID_VALUE = 0x8010_0011;
export const SCARD_E_SYSTEM_CANCELLED = 0x8010_0012;
export const SCARD_F_COMM_ERROR = 0x8010_0013;
export const SCARD_F_UNKNOWN_ERROR = 0x8010_0014;
export const SCARD_E_INVALID_ATR = 0x8010_0015;
export const SCARD_E_NOT_TRANSACTED = 0x8010_0016;
export const SCARD_E_READER_UNAVAILABLE = 0x8010_0017;
export const SCARD_P_SHUTDOWN = 0x8010_0018;
export const SCARD_E_PCI_TOO_SMALL = 0x8010_0019;
export const SCARD_E_READER_UNSUPPORTED = 0x8010_001A;
export const SCARD_E_DUPLICATE_READER = 0x8010_001B;
export const SCARD_E_CARD_UNSUPPORTED = 0x8010_001C;
export const SCARD_E_NO_SERVICE = 0x8010_001D;
export const SCARD_E_SERVICE_STOPPED = 0x8010_001E;
export const SCARD_E_UNEXPECTED = 0x8010_001F;
export const SCARD_E_ICC_INSTALLATION = 0x8010_0020;
export const SCARD_E_ICC_CREATEORDER = 0x8010_0021;
export const SCARD_E_DIR_NOT_FOUND = 0x8010_0023;
export const SCARD_E_FILE_NOT_FOUND = 0x8010_0024;
export const SCARD_E_NO_DIR = 0x8010_0025;
export const SCARD_E_NO_FILE = 0x8010_0026;
export const SCARD_E_NO_ACCESS = 0x8010_0027;
export const SCARD_E_WRITE_TOO_MANY = 0x8010_0028;
export const SCARD_E_BAD_SEEK = 0x8010_0029;
export const SCARD_E_INVALID_CHV = 0x8010_002A;
export const SCARD_E_UNKNOWN_RES_MNG = 0x8010_002B;
export const SCARD_E_NO_SUCH_CERTIFICATE = 0x8010_002C;
export const SCARD_E_CERTIFICATE_UNAVAILABLE = 0x8010_002D;
export const SCARD_E_NO_READERS_AVAILABLE = 0x8010_002E;
export const SCARD_E_COMM_DATA_LOST = 0x8010_002F;
export const SCARD_E_NO_KEY_CONTAINER = 0x8010_0030;
export const SCARD_E_SERVER_TOO_BUSY = 0x8010_0031;

export const SCARD_E_UNSUPPORTED_FEATURE = 0x8010_001F;

export const SCARD_W_UNSUPPORTED_CARD = 0x8010_0065;
export const SCARD_W_UNRESPONSIVE_CARD = 0x8010_0066;
export const SCARD_W_UNPOWERED_CARD = 0x8010_0067;
export const SCARD_W_RESET_CARD = 0x8010_0068;
export const SCARD_W_REMOVED_CARD = 0x8010_0069;
export const SCARD_W_SECURITY_VIOLATION = 0x8010_006A;
export const SCARD_W_WRONG_CHV = 0x8010_006B;
export const SCARD_W_CHV_BLOCKED = 0x8010_006C;
export const SCARD_W_EOF = 0x8010_006D;
export const SCARD_W_CANCELLED_BY_USER = 0x8010_006E;
export const SCARD_W_CARD_NOT_AUTHENTICATED = 0x8010_006F;
export const SCARD_W_CACHE_ITEM_NOT_FOUND = 0x8010_0070;
export const SCARD_W_CACHE_ITEM_STALE = 0x8010_0071;
export const SCARD_W_CACHE_ITEM_TOO_BIG = 0x8010_0072;

export const SCARD_SCOPE_USER = 0x0000;
export const SCARD_SCOPE_TERMINAL = 0x0001;
export const SCARD_SCOPE_SYSTEM = 0x0002;
export const SCARD_SCOPE_GLOBAL = 0x0003;

export const SCARD_PROTOCOL_UNDEFINED = 0x0000_0000;
export const SCARD_PROTOCOL_UNSET = SCARD_PROTOCOL_UNDEFINED;
export const SCARD_PROTOCOL_T0 = 0x0000_0001;
export const SCARD_PROTOCOL_T1 = 0x0000_0002;
export const SCARD_PROTOCOL_T15 = 0x0000_0008;
export const SCARD_PROTOCOL_ANY = SCARD_PROTOCOL_T0 | SCARD_PROTOCOL_T1;

export const SCARD_SHARE_EXCLUSIVE = 0x0001;
export const SCARD_SHARE_SHARED = 0x0002;
export const SCARD_SHARE_DIRECT = 0x0003;

export const SCARD_LEAVE_CARD = 0x0000;
export const SCARD_RESET_CARD = 0x0001;
export const SCARD_UNPOWER_CARD = 0x0002;
export const SCARD_EJECT_CARD = 0x0003;

export const SCARD_STATE_UNAWARE = 0x0000;
export const SCARD_STATE_IGNORE = 0x0001;
export const SCARD_STATE_CHANGED = 0x0002;
export const SCARD_STATE_UNKNOWN = 0x0004;
export const SCARD_STATE_UNAVAILABLE = 0x0008;
export const SCARD_STATE_EMPTY = 0x0010;
export const SCARD_STATE_PRESENT = 0x0020;
export const SCARD_STATE_ATRMATCH = 0x0040;
export const SCARD_STATE_EXCLUSIVE = 0x0080;
export const SCARD_STATE_INUSE = 0x0100;
export const SCARD_STATE_MUTE = 0x0200;
export const SCARD_STATE_UNPOWERED = 0x0400;

export const SCARD_AUTOALLOCATE = 0xFFFF_FFFF;

export const INFINITE = 0xFFFF_FFFF;

export const MAX_ATR_SIZE = 33;
export const SCARD_ATR_LENGTH = MAX_ATR_SIZE;
export const MAX_BUFFER_SIZE = 264;
export const MAX_BUFFER_SIZE_EXTENDED = 4 + 3 + (1 << 16) + 3 + 2;

export const SCARD_CLASS_VENDOR_INFO = 1;
export const SCARD_CLASS_COMMUNICATIONS = 2;
export const SCARD_CLASS_PROTOCOL = 3;
export const SCARD_CLASS_POWER_MGMT = 4;
export const SCARD_CLASS_SECURITY = 5;
export const SCARD_CLASS_MECHANICAL = 6;
export const SCARD_CLASS_VENDOR_DEFINED = 7;
export const SCARD_CLASS_IFD_PROTOCOL = 8;
export const SCARD_CLASS_ICC_STATE = 9;
export const SCARD_CLASS_SYSTEM = 0;

function SCARD_ATTR_VALUE(klass: number, value: number): number {
  return (klass << 16) | value;
}

export const SCARD_ATTR_VENDOR_NAME = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0100);
export const SCARD_ATTR_VENDOR_IFD_TYPE = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0101);
export const SCARD_ATTR_VENDOR_IFD_VERSION = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0102);
export const SCARD_ATTR_VENDOR_IFD_SERIAL_NO = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0103);
export const SCARD_ATTR_CHANNEL_ID = SCARD_ATTR_VALUE(SCARD_CLASS_COMMUNICATIONS, 0x0110);
export const SCARD_ATTR_ASYNC_PROTOCOL_TYPES = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0120);
export const SCARD_ATTR_DEFAULT_CLK = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0121);
export const SCARD_ATTR_MAX_CLK = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0122);
export const SCARD_ATTR_DEFAULT_DATA_RATE = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0123);
export const SCARD_ATTR_MAX_DATA_RATE = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0124);
export const SCARD_ATTR_MAX_IFSD = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0125);
export const SCARD_ATTR_SYNC_PROTOCOL_TYPES = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0126);
export const SCARD_ATTR_POWER_MGMT_SUPPORT = SCARD_ATTR_VALUE(SCARD_CLASS_POWER_MGMT, 0x0131);
export const SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE = SCARD_ATTR_VALUE(SCARD_CLASS_SECURITY, 0x0140);
export const SCARD_ATTR_USER_AUTH_INPUT_DEVICE = SCARD_ATTR_VALUE(SCARD_CLASS_SECURITY, 0x0142);
export const SCARD_ATTR_CHARACTERISTICS = SCARD_ATTR_VALUE(SCARD_CLASS_MECHANICAL, 0x0150);

export const SCARD_ATTR_CURRENT_PROTOCOL_TYPE = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0201);
export const SCARD_ATTR_CURRENT_CLK = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0202);
export const SCARD_ATTR_CURRENT_F = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0203);
export const SCARD_ATTR_CURRENT_D = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0204);
export const SCARD_ATTR_CURRENT_N = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0205);
export const SCARD_ATTR_CURRENT_W = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0206);
export const SCARD_ATTR_CURRENT_IFSC = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0207);
export const SCARD_ATTR_CURRENT_IFSD = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0208);
export const SCARD_ATTR_CURRENT_BWT = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0209);
export const SCARD_ATTR_CURRENT_CWT = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x020A);
export const SCARD_ATTR_CURRENT_EBC_ENCODING = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x020B);
export const SCARD_ATTR_EXTENDED_BWT = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x020C);

export const SCARD_ATTR_ICC_PRESENCE = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0300);
export const SCARD_ATTR_ICC_INTERFACE_STATUS = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0301);
export const SCARD_ATTR_CURRENT_IO_STATE = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0302);
export const SCARD_ATTR_ATR_STRING = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0303);
export const SCARD_ATTR_ICC_TYPE_PER_ATR = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0304);

export const SCARD_ATTR_ESC_RESET = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_DEFINED, 0xA000);
export const SCARD_ATTR_ESC_CANCEL = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_DEFINED, 0xA003);
export const SCARD_ATTR_ESC_AUTHREQUEST = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_DEFINED, 0xA005);
export const SCARD_ATTR_MAXINPUT = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_DEFINED, 0xA007);

export const SCARD_ATTR_DEVICE_UNIT = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0001);
export const SCARD_ATTR_DEVICE_IN_USE = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0002);
export const SCARD_ATTR_DEVICE_FRIENDLY_NAME_A = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0003);
export const SCARD_ATTR_DEVICE_SYSTEM_NAME_A = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0004);
export const SCARD_ATTR_DEVICE_FRIENDLY_NAME_W = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0005);
export const SCARD_ATTR_DEVICE_SYSTEM_NAME_W = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0006);
export const SCARD_ATTR_SUPRESS_T1_IFS_REQUEST = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0007);

export const SCARD_ATTR_DEVICE_FRIENDLY_NAME = SCARD_ATTR_DEVICE_FRIENDLY_NAME_A;
export const SCARD_ATTR_DEVICE_SYSTEM_NAME = SCARD_ATTR_DEVICE_SYSTEM_NAME_A;
